DATABASE:
  driver: "jdbc:mysql://"
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: "test_database"
  databaseProperties: "?useSSL=false&serverTimezone=UTC"
  maximumPoolSize: 10